### PR TITLE
upgrade Mocha

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Also please rerelease under a new name on npmjs.com.

**Comment by cosminghitea** [comment]
Well I try actually to convince the owner the update his library

**Comment by DanielRuf** [comment]
Would be great to see some progress there. If the project needs new / more maintainers then I would like to help too. Or move the project to an organization,

**Comment by cosminghitea** [comment]
Yep I'm on the same page as you.

**Pull request merged**
